/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processing_simpletouch_SimpleTouch */

#ifndef _Included_processing_simpletouch_SimpleTouch
#define _Included_processing_simpletouch_SimpleTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processing_simpletouch_SimpleTouch
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_processing_simpletouch_SimpleTouch_openDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     processing_simpletouch_SimpleTouch
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_processing_simpletouch_SimpleTouch_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processing_simpletouch_SimpleTouch
 * Method:    getTouches
 * Signature: (J)[Lprocessing/simpletouch/SimpleTouchEvt;
 */
JNIEXPORT jobjectArray JNICALL Java_processing_simpletouch_SimpleTouch_getTouches
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processing_simpletouch_SimpleTouch
 * Method:    closeDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_processing_simpletouch_SimpleTouch_closeDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
